# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/hephaestus/Documents/Utah State/School/Computer Architecture/ECE_5720_Cache_Lab"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/hephaestus/Documents/Utah State/School/Computer Architecture/ECE_5720_Cache_Lab"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/hephaestus/Documents/Utah State/School/Computer Architecture/ECE_5720_Cache_Lab/CMakeFiles" "/home/hephaestus/Documents/Utah State/School/Computer Architecture/ECE_5720_Cache_Lab//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/hephaestus/Documents/Utah State/School/Computer Architecture/ECE_5720_Cache_Lab/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named trans_obj

# Build rule for target.
trans_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trans_obj
.PHONY : trans_obj

# fast build rule for target.
trans_obj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trans_obj.dir/build.make CMakeFiles/trans_obj.dir/build
.PHONY : trans_obj/fast

#=============================================================================
# Target rules for targets named csim

# Build rule for target.
csim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csim
.PHONY : csim

# fast build rule for target.
csim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csim.dir/build.make CMakeFiles/csim.dir/build
.PHONY : csim/fast

#=============================================================================
# Target rules for targets named test-trans

# Build rule for target.
test-trans: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-trans
.PHONY : test-trans

# fast build rule for target.
test-trans/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-trans.dir/build.make CMakeFiles/test-trans.dir/build
.PHONY : test-trans/fast

#=============================================================================
# Target rules for targets named tracegen

# Build rule for target.
tracegen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tracegen
.PHONY : tracegen

# fast build rule for target.
tracegen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tracegen.dir/build.make CMakeFiles/tracegen.dir/build
.PHONY : tracegen/fast

cachelab.o: cachelab.c.o
.PHONY : cachelab.o

# target to build an object file
cachelab.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csim.dir/build.make CMakeFiles/csim.dir/cachelab.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-trans.dir/build.make CMakeFiles/test-trans.dir/cachelab.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tracegen.dir/build.make CMakeFiles/tracegen.dir/cachelab.c.o
.PHONY : cachelab.c.o

cachelab.i: cachelab.c.i
.PHONY : cachelab.i

# target to preprocess a source file
cachelab.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csim.dir/build.make CMakeFiles/csim.dir/cachelab.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-trans.dir/build.make CMakeFiles/test-trans.dir/cachelab.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tracegen.dir/build.make CMakeFiles/tracegen.dir/cachelab.c.i
.PHONY : cachelab.c.i

cachelab.s: cachelab.c.s
.PHONY : cachelab.s

# target to generate assembly for a file
cachelab.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csim.dir/build.make CMakeFiles/csim.dir/cachelab.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-trans.dir/build.make CMakeFiles/test-trans.dir/cachelab.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tracegen.dir/build.make CMakeFiles/tracegen.dir/cachelab.c.s
.PHONY : cachelab.c.s

csim.o: csim.c.o
.PHONY : csim.o

# target to build an object file
csim.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csim.dir/build.make CMakeFiles/csim.dir/csim.c.o
.PHONY : csim.c.o

csim.i: csim.c.i
.PHONY : csim.i

# target to preprocess a source file
csim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csim.dir/build.make CMakeFiles/csim.dir/csim.c.i
.PHONY : csim.c.i

csim.s: csim.c.s
.PHONY : csim.s

# target to generate assembly for a file
csim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csim.dir/build.make CMakeFiles/csim.dir/csim.c.s
.PHONY : csim.c.s

test-trans.o: test-trans.c.o
.PHONY : test-trans.o

# target to build an object file
test-trans.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-trans.dir/build.make CMakeFiles/test-trans.dir/test-trans.c.o
.PHONY : test-trans.c.o

test-trans.i: test-trans.c.i
.PHONY : test-trans.i

# target to preprocess a source file
test-trans.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-trans.dir/build.make CMakeFiles/test-trans.dir/test-trans.c.i
.PHONY : test-trans.c.i

test-trans.s: test-trans.c.s
.PHONY : test-trans.s

# target to generate assembly for a file
test-trans.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-trans.dir/build.make CMakeFiles/test-trans.dir/test-trans.c.s
.PHONY : test-trans.c.s

tracegen.o: tracegen.c.o
.PHONY : tracegen.o

# target to build an object file
tracegen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tracegen.dir/build.make CMakeFiles/tracegen.dir/tracegen.c.o
.PHONY : tracegen.c.o

tracegen.i: tracegen.c.i
.PHONY : tracegen.i

# target to preprocess a source file
tracegen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tracegen.dir/build.make CMakeFiles/tracegen.dir/tracegen.c.i
.PHONY : tracegen.c.i

tracegen.s: tracegen.c.s
.PHONY : tracegen.s

# target to generate assembly for a file
tracegen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tracegen.dir/build.make CMakeFiles/tracegen.dir/tracegen.c.s
.PHONY : tracegen.c.s

trans.o: trans.c.o
.PHONY : trans.o

# target to build an object file
trans.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trans_obj.dir/build.make CMakeFiles/trans_obj.dir/trans.c.o
.PHONY : trans.c.o

trans.i: trans.c.i
.PHONY : trans.i

# target to preprocess a source file
trans.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trans_obj.dir/build.make CMakeFiles/trans_obj.dir/trans.c.i
.PHONY : trans.c.i

trans.s: trans.c.s
.PHONY : trans.s

# target to generate assembly for a file
trans.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trans_obj.dir/build.make CMakeFiles/trans_obj.dir/trans.c.s
.PHONY : trans.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... csim"
	@echo "... test-trans"
	@echo "... tracegen"
	@echo "... trans_obj"
	@echo "... cachelab.o"
	@echo "... cachelab.i"
	@echo "... cachelab.s"
	@echo "... csim.o"
	@echo "... csim.i"
	@echo "... csim.s"
	@echo "... test-trans.o"
	@echo "... test-trans.i"
	@echo "... test-trans.s"
	@echo "... tracegen.o"
	@echo "... tracegen.i"
	@echo "... tracegen.s"
	@echo "... trans.o"
	@echo "... trans.i"
	@echo "... trans.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

